name: go-test example

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  LAUNCHABLE_DEBUG: 1
  LAUNCHABLE_REPORT_ERROR: 1
  LAUNCHABLE_ORGANIZATION: "launchableinc"
  LAUNCHABLE_WORKSPACE: "rocket-car-gotest"
  EXPERIMENTAL_GITHUB_OIDC_TOKEN_AUTH: 1

permissions:
  id-token: write
  contents: read

jobs:
  tests:
    env:
      LAUNCHABLE_TOKEN: ${{ secrets.LAUNCHABLE_GO_EXAMPLE_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Clone go-test example
        run: git clone https://github.com/launchableinc/examples.git
      - name: Install dependencies
        run: go install github.com/jstemmer/go-junit-report@latest
      - name: Record build action
        uses: ./
        with:
          build_name: $GITHUB_RUN_ID
          source_path: ./examples/go/
      - name: test
        run: cd examples/go && go test -v ./... 2>&1 | go-junit-report -set-exit-code > report.xml
      - name: Record test results to build action
        uses: launchableinc/record-test-results-to-build@v0.1.0
        with:
          build_name: $GITHUB_RUN_ID
          report_path: ./examples/go/
          test_runner: go-test
        if: always()